MED-2619 : Handle API key
medeo/hapi-fhir-jpaserver-starter pull request #8
Opened 2020-09-30 06:55 UTC by mariannemedeo

2020-09-30 12:18 UTC, Chzzs requested changes

2020-09-30 12:18 UTC, Chzzs commented on src/main/java/io/medeo/fhir/AWSCognitoTokenSecurityInterceptor.java
> +    String apiKey = theRequest.getHeader("MedeoAccessKeyId");
usually we use snake case for headers: 
`MEDEO_ACCESS_KEY_ID`

2020-09-30 12:19 UTC, Chzzs requested changes

2020-09-30 12:19 UTC, Chzzs commented on src/main/java/io/medeo/fhir/AWSCognitoTokenSecurityInterceptor.java
> +    String apiKey = theRequest.getHeader("MedeoAccessKeyId");
could you add some comments about the different authentication methods ?

2020-10-01 13:51 UTC, pauline-d approved these changes

2020-10-01 13:53 UTC, Chzzs approved these changes

2020-10-01 14:00 UTC, merged

2020-10-01 15:49 UTC, Chzzs commented
:tada: This PR is included in version 1.5.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: